apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: apigee-emulator
  name: apigee-emulator
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: apigee-emulator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apigee-emulator
    spec:
      containers:
      - image: gcr.io/apigee-release/hybrid/apigee-emulator:1.13.0
        name: apigee-emulator
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 8998
---
apiVersion: v1
kind: Service
metadata:
  name: apigee-emulator
spec:
  selector:
    app.kubernetes.io/name: apigee-emulator
  type: LoadBalancer
  ports:
    - name: controlport
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: trafficport
      protocol: TCP
      port: 8998
      targetPort: 8998