apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: energy-trading-service
  name: energy-trading-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: energy-trading-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: energy-trading-service
    spec:
      containers:
      - image: energy-trading-service:latest
        name: energy-trading-service
        ports:
        - containerPort: 8080