apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: energy-trading-service
  name: energy-trading-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: energy-trading-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: energy-trading-service
    spec:
      containers:
      - image: energy-trading-service:latest
        name: energy-trading-service
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: energy-trading-service
spec:
  selector:
    app.kubernetes.io/name: energy-trading-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080